module Pages.About exposing (update)

import LangWidget exposing (..)
import Types exposing (..)
import Html exposing (..)
import Menu exposing (..)
import Footer exposing (..)
import Html as H exposing (Html, text, div, img)
import Html.Attributes as A exposing (id, class, href, src, style, title, alt, type_, scope)
import Bootstrap.Grid as Grid
import I18Next exposing (t)

update : Model -> Html Msg
update model =
    div []
        [ div [class "nav-wrapper nav", id "nav"] [render_menu model]
        , langswitcher model
        , Grid.container [] [ content model ]
        , render_footer model
        ]


content : Model -> Html Msg
content model =
    div []
        [
            H.section [ class "about", id "about" ]
            [ div [ class "container text-xs-center" ]
                [ H.h2 [class "text-center"]
                [ text (t model.translations "about.maintitle") ]
                , div [ class "about-text" ]
                [ H.p []
                    [ H.strong []
                    [ text "Shivam Yoga" ], text (" " ++ (t model.translations "about.shivamyoga.p1"))
                    ]
                , H.p []
                    [ text (t model.translations "about.shivamyoga.p2") ]
                , H.p []
                    [ H.strong []
                    [ text (t model.translations "about.shivamyoga.sankhya.title") ], text (" " ++ (t model.translations "about.shivamyoga.sankhya.body"))
                    ]
                , H.p []
                    [ H.strong []
                    [ text (t model.translations "about.shivamyoga.tantra.title") ], text (" " ++ (t model.translations "about.shivamyoga.tantra.body"))
                    ]
                , H.p []
                    [ H.strong []
                    [ text (t model.translations "about.shivamyoga.expression") ]
                    ]
                ]
                ]
            ]
            ,H.section [ class "features", id "features" ]
            [ div [ class "container" ]
                [ H.h2 [ class "text-sm-center" ]
                [ text (t model.translations "about.features.title") ]
                , div [ class "row" ]
                [ div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-volume-down" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Dharana" ]
                        , H.p []
                        [ text (t model.translations "about.features.dharana") ]
                        ]
                    ]
                    ]
                , div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-exchange" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Pujas" ]
                        , H.p []
                        [ text (t model.translations "about.features.pujas") ]
                        ]
                    ]
                    ]
                , div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-user" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Pranayamas" ]
                        , H.p []
                        [ text (t model.translations "about.features.pranayamas") ]
                        ]
                    ]
                    ]
                ]
                , div [ class "row" ]
                [ div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-balance-scale" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Asanas" ]
                        , H.p []
                        [ text (t model.translations "about.features.asanas") ]
                        ]
                    ]
                    ]
                , div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-battery-full" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Bandhas" ]
                        , H.p []
                        [ text (t model.translations "about.features.bandhas") ]
                        ]
                    ]
                    ]
                , div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-sign-out" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Kriyas" ]
                        , H.p []
                        [ text (t model.translations "about.features.kriyas") ]
                        ]
                    ]
                    ]
                , div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-unlock-alt" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Yoganidra" ]
                        , H.p []
                        [ text (t model.translations "about.features.yoganidra") ]
                        ]
                    ]
                    ]
                , div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-heart" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Mantras" ]
                        , H.p []
                        [ text (t model.translations "about.features.mantras") ]
                        ]
                    ]
                    ]
                , div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-hand-paper-o" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Mudras" ]
                        , H.p []
                        [ text (t model.translations "about.features.mudras") ]
                        ]
                    ]
                    ]
                , div [ class "feature-col col-lg-4 col-xs-12" ]
                    [ div [ class "card card-block" ]
                    [ div []
                        [ div [ class "feature-icon" ]
                        [ H.span [ class "fa fa-circle" ]
                            []
                        ]
                        ]
                    , div []
                        [ H.h3 []
                        [ text "Dhyana" ]
                        , H.p []
                        [ text (t model.translations "about.features.dhyana") ]
                        ]
                    ]
                    ]
                ]
                ]
            ]
        ]