module Footer exposing (render_footer)

import Types exposing (..)
import Html as H exposing (Html, text, div, img)
import Html.Attributes as A exposing (id, class, href, src, style, title, alt, type_, scope)
import I18Next exposing (t)


render_footer : Model -> Html Msg
render_footer model =
    H.footer []
        [ H.footer [ class "site-footer", id "contact" ]
            [ div [ class "container" ]
                [ div [ class "row" ]
                [ div [ class "footer-col col-sm-12 col-lg-6 text-xs-center text-lg-left" ]
                    [ H.h2 []
                    [ text (t model.translations "footer.contactus") ]
                    , div [ class "cta" ]
                    [ H.a [ href "tel:+817044408396" ]
                        [ H.i [ class "fa fa-phone" ]
                        [] ,text "070-4440-8396"
                        ]
                    ]
                    , div [ class "cta" ]
                    [ H.a [ href "mailto:miki@ahimsayoga.jp" ]
                        [ H.i [ class "fa fa-envelope" ]
                        [] ,text "miki@ahimsayoga.jp"
                        ]
                    ]
                    , H.nav [ class "nav social-nav footer-social-nav" ]
                    [ H.a [ href "http://facebook.com/ahimsayogajp" ]
                        [ H.i [ class "fa fa-facebook" ]
                        []
                        ]
                    , H.a [ href "http://instagram.com/ahimsayogajp" ]
                        [ H.i [ class "fa fa-instagram" ]
                        []
                        ]
                    , H.a [ href "http://twitter.com/ahimsayogajp" ]
                        [ H.i [ class "fa fa-twitter" ]
                        []
                        ]
                    , H.a [ href "https://www.youtube.com/channel/UCihAjjXntS8Q-5a4wBIolgQ" ]
                        [ H.i [ class "fa fa-youtube" ]
                        []
                        ]
                    ]
                    ]
                , div [ class "footer-col col-sm-12 col-lg-6 text-xs-center text-lg-left" ]
                    [ H.p [ class "footer-text" ]
                    [ text (t model.translations "footer.body") ]
                    ]
                ]
                ]
            , div [ class "bottom" ]
                [ div [ class "container" ]
                [ div [ class "row" ]
                    [ div [ class "col-lg-9 col-xs-12" ]
                    [ H.ul [ class "list-inline" ]
                        [ H.li [ class "list-inline-item" ]
                        [ H.a [ href "/" ]
                            [ text (t model.translations "nav.home") , H.span [ class "sr-only" ]
                            [ text "Toggle navigation" ]
                            ]
                        ]
                        , H.li [ class "list-inline-item" ]
                        [ H.a [ href "about" ]
                            [ text (t model.translations "nav.about") ]
                        ]
                        , H.li [ class "list-inline-item" ]
                        [ H.a [ href "schedule" ]
                            [ text (t model.translations "nav.schedule") ]
                        ]
                        , H.li [ class "list-inline-item" ]
                        [ H.a [ href "instructors" ]
                            [ text (t model.translations "nav.instructors") ]
                        ]
                        , H.li [ class "list-inline-item" ]
                        [ H.a [ href "contact" ]
                            [ text (t model.translations "nav.contact") ]
                        ]
                        ]
                    ]
                    , div [ class "col-lg-3 col-xs-12 text-lg-right text-xs-center" ]
                    [ H.p [ class "copyright-text" ]
                        [ text "© "  ,H.a [ href "http://ahimsalife.jp" ]
                        [ text "Ahimsa Life" ] ,text ", Japan"
                        ]
                    ]
                    ]
                ]
                ]
            ]
        ]
